version: '3'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=woodshopapi.piikl.com
      - LETSENCRYPT_HOST=woodshopapi.piikl.com
      - LETSENCRYPT_EMAIL=info@piikl.com
  frontend:
    build: ./frontend
    ports:
      - "8082:80"
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=woodshop.piikl.com
      - LETSENCRYPT_HOST=woodshop.piikl.com
      - LETSENCRYPT_EMAIL=info@piikl.com